[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Fix for the /search/page: /search error
[[redirects]]
  from = "/search/page"
  to = "/search"
  status = 301
  force = true

[[redirects]]
  from = "/search/page/*"
  to = "/search/:splat"
  status = 301
  force = true
